

services:
  db:
    image: postgres:16
    container_name: fintrack-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: thql99@
      POSTGRES_DB: fintrack_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
